version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    user: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=REDACTED_PASSWORD
    network_mode: host
    logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5" 
