# Generated by Django 3.2.16 on 2023-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdbEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliases', models.CharField(max_length=512)),
                ('types', models.CharField(max_length=512)),
                ('host', models.CharField(max_length=256)),
                ('hostra', models.FloatField()),
                ('hostdec', models.FloatField()),
                ('hostoffsetang', models.FloatField()),
                ('hostoffsetdist', models.FloatField()),
                ('ra', models.FloatField()),
                ('ra_degrees', models.FloatField()),
                ('dec', models.FloatField()),
                ('dec_degrees', models.FloatField()),
                ('num_spectra', models.IntegerField()),
                ('num_photometry', models.IntegerField()),
                ('maxabsmag', models.FloatField()),
                ('maxappmag', models.FloatField()),
                ('maxband', models.CharField(max_length=5)),
                ('maxdate', models.DateTimeField()),
                ('maxvisualabsmag', models.FloatField()),
                ('maxvisualappmag', models.FloatField()),
                ('maxvisualband', models.CharField(max_length=5)),
                ('maxvisualdate', models.DateTimeField()),
                ('discoverdate', models.DateField()),
                ('discoverer', models.CharField(max_length=512)),
                ('redshift', models.FloatField()),
                ('velocity', models.FloatField()),
                ('lumdist', models.FloatField()),
                ('filename', models.CharField(max_length=1024)),
                ('dirname', models.CharField(max_length=2048)),
                ('repoUrl', models.CharField(max_length=2048)),
            ],
        ),
    ]
