# Generated by Django 3.2.16 on 2023-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdbentry',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='dec_degrees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='dirname',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='discoverdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='discoverer',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='filename',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='host',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostdec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostoffsetang',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostoffsetdist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='lumdist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxabsmag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxappmag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxband',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxvisualabsmag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxvisualappmag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxvisualband',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='maxvisualdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='num_photometry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='num_spectra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='ra_degrees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='redshift',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='repoUrl',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='velocity',
            field=models.FloatField(null=True),
        ),
    ]
