# Generated by Django 3.2.16 on 2023-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbapp', '0003_auto_20230201_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdbentry',
            name='hostdec_degrees',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sdbentry',
            name='hostra_degrees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostdec',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='hostra',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
