# Generated by Django 3.2.16 on 2023-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbapp', '0004_auto_20230201_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdbentry',
            name='name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
