# Generated by Django 3.2.16 on 2023-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbapp', '0005_sdbentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdbentry',
            name='aliases',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sdbentry',
            name='types',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
